### ISSUE TITLE
AV Detection

### ISSUE THREAD

**Issue by travexyz** [szajjch/c4ndyGrabber#5]
Av is detecting web request and blocking the execution, might need a bypass. Someone?

**Comment by OlMi1** [comment]
What happens if you run it as administrator?

**Comment by AnonHexo** [comment]
> What happens if you run it as administrator?

same thing

**Comment by AstroOnYT** [comment]
use fud

**Comment by AnonHexo** [comment]
> use fud

what is fud

**Comment by CodeDiseaseDev** [comment]
lol
